### ISSUE TITLE
Very long field names in Structs, refer types.go

### ISSUE THREAD

**Issue by Longwater1234** [Golang-Tanzania/GoPesa#16]
https://github.com/Golang-Tanzania/mpesa/blob/5b6a0281796c62e53b4a448090856d62fa7f296b/types.go#L80

I noticed the new structs have "Output..." prefix in each field. I understand the final JSON request body have this, but do we really need this in the struct itself in this go API library ? i think it's too verbose in my opinion. I think the "json.." tag is enough,  but the actual struct should be brief. 

This applies for both Request and Response structs. as shown here. 
So i propose `ResponseDesc` from `OutputResponseDesc`

**Comment by Hopertz** [comment]
> https://github.com/Golang-Tanzania/mpesa/blob/5b6a0281796c62e53b4a448090856d62fa7f296b/types.go#L80
> 
> I noticed the new structs have "Output..." prefix in each field. I understand the final JSON request body have this, but do we really need this in the struct itself in this go API library ? i think it's too verbose in my opinion. I think the "json.." tag is enough, but the actual struct should be brief.
> 
> This applies for both Request and Response structs. as shown here. So i propose `ResponseDesc` from `OutputResponseDesc`

Yeah, I totally agree with that, waiting for the fix  /:

**Comment by Hopertz** [comment]
@Longwater1234  don't you think its great to maintain consistency between the json tag name and struct field name?  https://github.com/Golang-Tanzania/mpesa/blob/5b6a0281796c62e53b4a448090856d62fa7f296b/types.go#L80

**Comment by Longwater1234** [comment]
@Hopertz yes, For the API user, this is too verbose, very long. I think it's unnecessary. Let's keep it brief but understandable. Internals should not concern the end user.

**Comment by Hopertz** [comment]
> @Hopertz yes, For the API user, this is too verbose, very long. I think it's unnecessary. Let's keep it brief but understandable. Internals should not concern the end user.

Yeah, I have time.  I will fix that ASAP.
