### ISSUE TITLE
Can we swap `map[string]string` with actual Structs 

### ISSUE THREAD

**Issue by Longwater1234** [Golang-Tanzania/GoPesa#6]
- I am proposing if we could define actual data structs for the body of API,  instead of generic `map[string]string`. This would enforce the type safety of Go.

**Comment by Hopertz** [comment]
Absolutely, you're right. In addition to that, it also improves code readability and enables compile-time checks. You can go ahead and make those changes.

**Comment by Longwater1234** [comment]
@Hopertz Alright, sawa. But where would I get the list of all **data types** used in Mpesa API? Can you kindly provide link, then i will make the changes.

**Comment by Hopertz** [comment]
@Longwater1234  I will have a look and send it to you.

**Comment by Hopertz** [comment]
@Longwater1234  use this link  [Link to open api portal ](https://openapiportal.m-pesa.com) . Create account and  then you are able to view the api documentation.

**Comment by Longwater1234** [comment]
@Hopertz Seen. Working on it

**Comment by Longwater1234** [comment]
i have made a pull request #12 . You can try it out before merge. I have **NOT** implemented the types, just declared them. Since you said you plan to rewrite the library, you may decide how you would use them.

I simply added a simple example, (commented out), in the code, using the types for REQUEST and RESPONSE.

**Comment by Hopertz** [comment]
@Longwater1234  thanks, I will have a look on it today.
