### ISSUE TITLE
Proposal: All public methods should return (result,error): golang style

### ISSUE THREAD

**Issue by Longwater1234** [Golang-Tanzania/GoPesa#8]
As i am working on issue #6, i have noticed we simply return `string` for public methods, and just log the error. 

But since this package library may be used as a **dependency** in OTHER projects, i think it's better let the caller handle the error, and return `nil` on empty result. 

In short, i propose we use the Go convention of returning 2 items: `(result , err )`

**Comment by Longwater1234** [comment]
We can still log the errors to console, but eventually we return the `error` to caller immediately.

**Comment by Hopertz** [comment]
@Longwater1234, yes, you are correct. By the way, we wrote this package when we were beginners. I am also planning a major rewrite.

**Comment by Longwater1234** [comment]
@Hopertz Alright, that will be great. Let me make a pull request for issue #6

**Comment by Longwater1234** [comment]
@Hopertz   Also, You may want to look at the GET requests you used. According to Mpesa Docs, the query params should be appended to URL, [key=value...], not in Request body

**Comment by Hopertz** [comment]
@Longwater1234 I don't think so,  btw I can't login to  Mpesa Docs to confirm it. Just send me a screenshot Tg same username.

**Comment by Longwater1234** [comment]
![1_Capture](https://github.com/Golang-Tanzania/GoPesa/assets/33986524/c94daff3-0a11-4a77-ae23-0c49d2d2ed72)
![2_Capture](https://github.com/Golang-Tanzania/GoPesa/assets/33986524/76c74d2b-6a67-455f-abff-4441c9dbf38b)


see the images i attached. @Hopertz

**Comment by Hopertz** [comment]
@Longwater1234 see the following screenshot from mpesa documentation

![photo_2023-10-12_20-08-56](https://github.com/Golang-Tanzania/GoPesa/assets/51443149/97a2d786-7f82-46f2-9d4c-62aabee625e7)

**Comment by Longwater1234** [comment]
Yes, but in your code for GET requests, you have put json in the body, instead of URL parameters

**Comment by Hopertz** [comment]
> Yes, but in your code for GET requests, you have put json in the body, instead of URL parameters

It was a mistake, but i wonder it was working.

**Comment by Hopertz** [comment]
> @Hopertz Also, You may want to look at the GET requests you used. According to Mpesa Docs, the query params should be appended to URL, [key=value...], not in Request body

Now its fixed and its working.
